name: neuralnet
services:
  boosted-lorenzetti:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/neuralnet:${DOCKER_TAG}
    container_name: neuralnet-container-${DOCKER_TAG}
    volumes:
      - ./:/root/workspaces/neuralnet
      - ~/logs:/root/logs
      - ~/data:/root/data
    tty: true
